/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';
import Thing from '../api/thing/thing.model';
import User from '../api/user/user.model';
import OrdenMatricula from '../api/orden_matricula/orden_matricula.model';

Thing.find({}).removeAsync()
  .then(() => {
    Thing.create({
      name: 'Development Tools',
      info: 'Integration with popular tools such as Bower, Grunt, Babel, Karma, ' +
        'Mocha, JSHint, Node Inspector, Livereload, Protractor, Jade, ' +
        'Stylus, Sass, and Less.'
    }, {
      name: 'Server and Client integration',
      info: 'Built with a powerful and fun stack: MongoDB, Express, ' +
        'AngularJS, and Node.'
    }, {
      name: 'Smart Build System',
      info: 'Build system ignores `spec` files, allowing you to keep ' +
        'tests alongside code. Automatic injection of scripts and ' +
        'styles into your index.html'
    }, {
      name: 'Modular Structure',
      info: 'Best practice client and server structures allow for more ' +
        'code reusability and maximum scalability'
    }, {
      name: 'Optimized Build',
      info: 'Build process packs up your templates as a single JavaScript ' +
        'payload, minifies your scripts/css/images, and rewrites asset ' +
        'names for caching.'
    }, {
      name: 'Deployment Ready',
      info: 'Easily deploy your app to Heroku or Openshift with the heroku ' +
        'and openshift subgenerators'
    });
  });

User.find({}).removeAsync()
  .then(() => {
    User.createAsync({
        provider: 'local',
        name: 'Test User',
        email: 'test@example.com',
        password: 'test'
      }, {
        provider: 'local',
        role: 'administrador',
        name: 'Admin',
        email: 'admin@example.com',
        password: 'admin'
      }, {
        provider: 'local',
        role: 'secretaria',
        name: 'Secretaria',
        email: 'secretaria@example.com',
        password: 'secretaria'
      })
      .then(() => {
        console.log('finished populating users');
      });
  });

OrdenMatricula.find({}).removeAsync().then(() => {
  OrdenMatricula.createAsync({
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "_id": "56ec28ba85234c08247d2555",
    "_numOrden": "AM3893",
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": "2000-02-10T05:00:00.000Z",
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "1234567894",
    "cargoMadre": "Jefa",
    "telefonosRepresentanteP": "+593994349012",
    "telefonosRepresentanteA": "+593224578163",
    "__v": 0,
    "contactoMadre": "234234",
    "contactoPadre": "23423424",
    "emailRepresentanteEconP": "234234@wrsfd",
    "paralelo": "D",
    "provinciaNacimiento": 4,
    "representanteEcon": "Adfsdfsdf",
    "representanteEconDir": "34534wsdf",
    "representanteEconID": "1234567891",
    "telefonoRepresentanteEconP": "34234",
    "tipoSangre": 1,
    "personasConvive": ["Padre"],
    "date": "2016-02-22T20:14:04.893Z",
    "active": true,
    "nivelAplica": "Segundo de básica",
    "nombreCompletoMadre": "Rockefeller Ortega Angie Elizabeth",
    "nombreCompletoPadre": "Muñoz Ortega Fabrizio David",
    "nombreCompleto": "Muñoz Rockefeller Alejandro Daniel",
    "id": "56ec28ba85234c08247d2555"
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 1,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 4,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 6,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 2,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 4,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 3,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 5,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 5,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }, {
    "nombres": "Alejandro Daniel",
    "apellidos": "Muñoz Rockefeller",
    "ID": "0923763184",
    "fechaNacimiento": new Date("2000-02-10T05:00:00.000Z"),
    "lugarNacimiento": "Ernesto Maldonado",
    "sexo": "M",
    "lugarDomicilio": "Cdla. Los Alames Mz 218 V 17",
    "nivel": 1,
    "anteriorInstitucion": "Mariscal Sucre",
    "representante": "Fabrizio David Anchundia Moreira",
    "representanteParentesco": "Padre",
    "representanteID": "0931473755",
    "emailRepresentanteP": "fanchundpo@hotmail.clm",
    "nombresPadre": "Fabrizio David",
    "apellidosPadre": "Muñoz Ortega",
    "lugarTrabajoPadre": "Casa",
    "idPadre": "0931473755",
    "cargoPadre": "Jefe",
    "nivelPadre": 3,
    "nombresMadre": "Angie Elizabeth",
    "apellidosMadre": "Rockefeller Ortega",
    "lugarTrabajoMadre": "Telegrafo",
    "idMadre": "0912345677",
    "cargoMadre": "Jefa",
    "nivelMadre": 2,
    telefonosRepresentanteP: "+593994349012",
    telefonosRepresentanteA: "+593224578163",
    "personasConvive": [
      "Padre"
    ],
    "date": new Date("2016-02-22T20:14:04.893Z"),
    "active": false
  }).then(() => {
    console.log('finished populating ordenes de matricula');
  });
});
